version: '3'

services:
  web:
    build: .
    ports:
      - 5000:8080
    expose:
      - 5000
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=BLUEZONE
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: