version: '3.8'
services:
  db:
    image: "mysql:8.0"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    restart: always
    volumes:
      - db:/var/lib/mysql
  web:
    depends_on:
      - db
    build: .
    restart: always
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    expose:
      - 8080
    environment:
      - DB_HOST=db
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - APIKEY-$APIKEY
    stdin_open: true
    tty: true
volumes:
  db: